### ISSUE TITLE
Allow save/load of polynomial coefficients

### ISSUE THREAD

**Issue by nibrunie** [kalray/metalibm#57]
Some function implementation (e.g. current meta tanh) requires a lot of polynomial approximations.
Those approximations are often used in multiple variants (scalar, v2, v4, f8). Currently they have to be found / verified each time.
An interesting feature could be to allow saving/loading polynomial coefficient from an external file.
With the proper predicate / verification, this feature would speed up some generations a lot.

**Comment by nibrunie** [comment]
[Request for Comment]
The idea will be to have a format containing: a list of polynomial approximations

Each approximation would be uniquely identified by
- formal approximated function expression
- approximation range
- degree
- coefficient formats
- error bound
- forced odd / forced even / no constraint 

Each approximation would be stored as an indexed map of numerical coefficients

**Comment by nibrunie** [comment]
```
approximated_fct: exp(x)
type: piecewise_polynomial_uniform_deg
approximation_range: Interval(0, 1)
error_target: dar(2**-25)
approximation:
  - step: 
      sub_approx_range: [0, 0.5]
      sub_approx: Polynomial([0, 1])
```
